name: trial_antara
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  webview_flutter: ^3.0.4
  json_annotation: ^4.6.0
  http: ^0.13.5
  provider:
  flutter_spinkit: ^5.1.0
  # get_it_mixin: ^3.1.4
  # get_it: ^7.2.0

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

