name: trial_antara
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  webview_flutter: ^3.0.4
  json_annotation: ^4.6.0
  http: ^0.13.5
  provider: any
  flutter_spinkit: ^5.1.0
  firebase_core: 1.24.0
  firebase_auth: 3.11.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/images/
  uses-material-design: true

